### ISSUE TITLE
Navbar dropdown not working

### ISSUE THREAD

**Issue by samueldy** [byrnereese/mkdocs-bootstrap4#1]
Hello,

I'm having trouble getting the nav dropdown to show nested files. Here is my `mkdocs.yml`:

```yaml
site_name: My Test Site
nav:
  - Home: index.md
  - About: about.md
  - Notebook Pages:
    - First Steps:
      - 01 - The Data Directory.md
      - 02 - The Sidebar.md
      - 03 - The Middlebar.md
      - 04 - The Mainbar.md
      - Third Level:
        - 05 - Notes.md
        - 06 - Tags.md
        - 07 - Shortcuts.md
        - 08 - Importing.md
        - 09 - Multi-Note Editing.md
theme: bootstrap4
```

In the attached screenshot, I expect to see the Notebook Pages menu drop down, but when I click on it, it does nothing.

![capture](https://user-images.githubusercontent.com/43612797/52456038-0f2c7e00-2b21-11e9-8185-1caed4a82173.PNG)

I installed `mkdocs-bootstrap4` with pip on Anaconda Python 3.7.1 running on Windows 10. Can you help?

Thanks!
